#target photoshop
s2t = stringIDToTypeID;

(r = new ActionReference()).putProperty(s2t('property'), p = s2t('smartObjectMore'));
r.putEnumerated(s2t('layer'), s2t('ordinal'), s2t('targetEnum'));
(d = new ActionDescriptor()).putObject(s2t('object'), s2t('object'), executeActionGet(r));
$.writeln(executeAction(s2t('convertJSONdescriptor'), d).getString(s2t('json')));

var idTrnf = charIDToTypeID( "Trnf" );
    var desc256 = new ActionDescriptor();
    var idFTcs = charIDToTypeID( "FTcs" );
    var idQCSt = charIDToTypeID( "QCSt" );
    var idQcsa = charIDToTypeID( "Qcsa" );
    desc256.putEnumerated( idFTcs, idQCSt, idQcsa );
    var idOfst = charIDToTypeID( "Ofst" );
        var desc257 = new ActionDescriptor();
        var idHrzn = charIDToTypeID( "Hrzn" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc257.putUnitDouble( idHrzn, idPxl, 20.700988 );
        var idVrtc = charIDToTypeID( "Vrtc" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc257.putUnitDouble( idVrtc, idPxl, -29.281881 );
    var idOfst = charIDToTypeID( "Ofst" );
    desc256.putObject( idOfst, idOfst, desc257 );
    var idWdth = charIDToTypeID( "Wdth" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc256.putUnitDouble( idWdth, idPrc, 84.515785 );
    var idHght = charIDToTypeID( "Hght" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc256.putUnitDouble( idHght, idPrc, 59.658632 );
    var idSkew = charIDToTypeID( "Skew" );
        var desc258 = new ActionDescriptor();
        var idHrzn = charIDToTypeID( "Hrzn" );
        var idAng = charIDToTypeID( "#Ang" );
        desc258.putUnitDouble( idHrzn, idAng, -38.351688 );
        var idVrtc = charIDToTypeID( "Vrtc" );
        var idAng = charIDToTypeID( "#Ang" );
        desc258.putUnitDouble( idVrtc, idAng, 0.000000 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc256.putObject( idSkew, idPnt, desc258 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc256.putUnitDouble( idAngl, idAng, -25.588258 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc259 = new ActionDescriptor();
        var idHrzn = charIDToTypeID( "Hrzn" );
        var idPrc = charIDToTypeID( "#Prc" );
        desc259.putUnitDouble( idHrzn, idPrc, -0.010614 );
        var idVrtc = charIDToTypeID( "Vrtc" );
        var idPrc = charIDToTypeID( "#Prc" );
        desc259.putUnitDouble( idVrtc, idPrc, -0.008455 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc256.putObject( idUsng, idPnt, desc259 );
    var idreplaceLayer = stringIDToTypeID( "replaceLayer" );
        var desc260 = new ActionDescriptor();
        var idFrom = charIDToTypeID( "From" );
            var ref1 = new ActionReference();
            var idLyr = charIDToTypeID( "Lyr " );
            ref1.putIdentifier( idLyr, 2 );
        desc260.putReference( idFrom, ref1 );
        var idT = charIDToTypeID( "T   " );
            var ref2 = new ActionReference();
            var idLyr = charIDToTypeID( "Lyr " );
            ref2.putIdentifier( idLyr, 2 );
        desc260.putReference( idT, ref2 );
    var idTrnf = charIDToTypeID( "Trnf" );
    desc256.putObject( idreplaceLayer, idTrnf, desc260 );
executeAction( idTrnf, desc256, DialogModes.NO );